### ISSUE TITLE
Coordinate system of imu output

### ISSUE THREAD

**Issue by vik748** [KumarRobotics/imu_vn_100#17]
Hey folks,
I have possibly quite a stupid question.  I was looking at the definition of coordinate system on the VN-100 which is given as 
<img src="https://user-images.githubusercontent.com/23345159/32706932-7e5392d8-c7ee-11e7-9e63-b65e4346d189.png" width="300" >
However, when I run the sensor with this driver, I see that the z - linear acceleration shows -9.8 ish values.  How does this match the provided coordinate system?  Is there some kind of coordinate transformation being done in the driver?

**Comment by ke-sun** [comment]
The measurement given by the driver is correct if the IMU is positioned as the figure shows. It is probably easier to think that the accelerometer measures the force instead of the gravity acceleration. Since the supporting force is upwards (in the negative z-axis), the reading from the z axis should be negative.
